-- Инициализация локальной базы данных Layndaru (PostgreSQL)

-- 1. Таблица общежитий (dormitories)
CREATE TABLE IF NOT EXISTS dormitories (
    id SERIAL PRIMARY KEY,
    number INTEGER NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(255)
);

-- 2. Таблица комнат (rooms)
CREATE TABLE IF NOT EXISTS rooms (
    idroom INTEGER PRIMARY KEY
);

-- 3. Таблица жителей (residents)
CREATE TABLE IF NOT EXISTS residents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tg_id BIGINT,
    vk_id BIGINT,
    max_id BIGINT,
    language TEXT DEFAULT 'RU',
    dormitory_id INTEGER REFERENCES dormitories(id) ON DELETE SET NULL DEFAULT 1,
    inidroom INTEGER REFERENCES rooms(idroom) ON DELETE SET NULL,
    idcards VARCHAR(50) UNIQUE,
    last_name VARCHAR(100),
    first_name VARCHAR(100),
    patronymic VARCHAR(100),
    notify_unconfirmed BOOLEAN NOT NULL DEFAULT true,
    is_banned BOOLEAN NOT NULL DEFAULT false,
    score INTEGER NOT NULL DEFAULT 100,
    confirm_streak INTEGER NOT NULL DEFAULT 0,
    miss_streak INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_residents_tg_id ON residents(tg_id);
CREATE INDEX IF NOT EXISTS idx_residents_vk_id ON residents(vk_id);
CREATE INDEX IF NOT EXISTS idx_residents_max_id ON residents(max_id);
CREATE INDEX IF NOT EXISTS idx_residents_dormitory ON residents(dormitory_id);
CREATE INDEX IF NOT EXISTS idx_residents_idcards ON residents(idcards);
CREATE INDEX IF NOT EXISTS idx_residents_fio ON residents(last_name, first_name);
CREATE INDEX IF NOT EXISTS idx_residents_score ON residents(score);

-- 3.1. Журнал баллов дисциплины (resident_score_logs)
CREATE TABLE IF NOT EXISTS resident_score_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resident_id BIGINT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
    booking_id BIGINT REFERENCES booking(id) ON DELETE SET NULL,
    delta INTEGER NOT NULL,
    score_after INTEGER NOT NULL,
    reason VARCHAR(50) NOT NULL,
    details TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_score_logs_resident ON resident_score_logs(resident_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_score_logs_booking ON resident_score_logs(booking_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_score_logs_booking_reason ON resident_score_logs(booking_id, reason);

-- 4. Таблица машин (machines)
-- status: 1 = Работает, 0 = Отключена
CREATE TABLE IF NOT EXISTS machines (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dormitory_id INTEGER REFERENCES dormitories(id) ON DELETE CASCADE DEFAULT 1,
    status SMALLINT DEFAULT 1,
    type_machine VARCHAR(50) NOT NULL,
    number_machine INTEGER
);

CREATE INDEX IF NOT EXISTS idx_machines_status_type ON machines(status, type_machine);
CREATE INDEX IF NOT EXISTS idx_machines_dormitory ON machines(dormitory_id);

-- 5. Таблица бронирований (booking)
-- status: 'Ожидание', 'Ожидание подтверждения', 'Подтверждено', 'Отменено'
CREATE TABLE IF NOT EXISTS booking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dormitory_id INTEGER REFERENCES dormitories(id) ON DELETE CASCADE DEFAULT 1,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    inidresidents BIGINT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
    inidmachine INTEGER REFERENCES machines(id) ON DELETE CASCADE,
    status VARCHAR(50) DEFAULT 'Ожидание',
    reminded_tg BOOLEAN DEFAULT FALSE,
    reminded_vk BOOLEAN DEFAULT FALSE,
    reminded_max BOOLEAN DEFAULT FALSE,
    is_autocanceled BOOLEAN DEFAULT FALSE,
    canceled_notified_tg BOOLEAN DEFAULT FALSE,
    canceled_notified_vk BOOLEAN DEFAULT FALSE,
    canceled_notified_max BOOLEAN DEFAULT FALSE,
    finish_notified_tg BOOLEAN DEFAULT FALSE,
    finish_notified_vk BOOLEAN DEFAULT FALSE,
    finish_notified_max BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_booking_machine_time ON booking(inidmachine, start_time, end_time);
CREATE INDEX IF NOT EXISTS idx_booking_residents ON booking(inidresidents);
CREATE INDEX IF NOT EXISTS idx_booking_dormitory ON booking(dormitory_id);
CREATE INDEX IF NOT EXISTS idx_booking_status ON booking(status);

-- 6. Таблица уведомлений (notifications)
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_residents BIGINT NOT NULL REFERENCES residents(id) ON DELETE CASCADE,
    id_machines INTEGER REFERENCES machines(id) ON DELETE SET NULL,
    create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    description TEXT
);


CREATE INDEX IF NOT EXISTS idx_notifications_resident ON notifications(id_residents);

-- =============================================================================
-- НАЧАЛЬНЫЕ ДАННЫЕ (SEEDS)
-- =============================================================================

-- Общежития КузГТУ
INSERT INTO dormitories (number, name, address) VALUES 
(1, 'Общежитие №1', 'ул. Мичурина, 57'),
(2, 'Общежитие №2', 'ул. Мичурина, 57а'),
(3, 'Общежитие №3', 'ул. Мичурина, 59'),
(4, 'Общежитие №4', 'ул. 50 лет Октября, 17'),
(5, 'Общежитие №5', 'пр. Ленинградский, 30')
ON CONFLICT (number) DO NOTHING;

-- Комнаты
INSERT INTO rooms (idroom) VALUES 
(101), (102), (103), (201), (202), (203), (301), (302), (303), (401), (402), (403), (906)
ON CONFLICT (idroom) DO NOTHING;

-- Машины только для Общежитий №3 и №4
INSERT INTO machines (dormitory_id, type_machine, number_machine, status) VALUES 
-- Общежитие №3
(3, 'Стиральная', 1, 1),
(3, 'Стиральная', 2, 1),
(3, 'Стиральная', 3, 1),
(3, 'Стиральная', 4, 1),
(3, 'Сушильная',  1, 1),
(3, 'Сушильная',  2, 1),
-- Общежитие №4
(4, 'Стиральная', 1, 1),
(4, 'Стиральная', 2, 1),
(4, 'Стиральная', 3, 1),
(4, 'Стиральная', 4, 1),
(4, 'Сушильная',  1, 1),
(4, 'Сушильная',  2, 1)
ON CONFLICT DO NOTHING;

-- Тестовые жильцы (Общежития №3 и №4 — где есть оборудование)
-- ========================================================================
-- Для входа в бота используйте номер студенческого билета / зачётки (idcards):
--   252004 — Анисимов Ростислав Дмитриевич, Общежитие №3, комн. 906 (Доступ: Активен)
--   111111 — Иванов Иван Сергеевич,         Общежитие №3, комн. 301 (Доступ: Активен)
--   222222 — Петрова Мария Александровна,   Общежитие №3, комн. 302 (Доступ: Активен)
--   333333 — Сидоров Алексей Дмитриевич,     Общежитие №4, комн. 401 (Доступ: Активен)
--   444444 — Козлова Анна Игоревна,        Общежитие №4, комн. 402 (Доступ: Активен)
--   555555 — Волков Дмитрий Олегович,       Общежитие №3, комн. 303 (Доступ: Активен)
-- ========================================================================
INSERT INTO residents (dormitory_id, last_name, first_name, patronymic, inidroom, idcards, language, score, is_banned) VALUES 
(3, 'Анисимов', 'Ростислав', 'Дмитриевич',   906, '252004', 'RU', 85,  false),
(3, 'Иванов',   'Иван',      'Сергеевич',     301, '111111', 'RU', 100, false),
(3, 'Петрова',  'Мария',     'Александровна', 302, '222222', 'RU', 95,  false),
(4, 'Сидоров',  'Алексей',   'Дмитриевич',    401, '333333', 'RU', 85,  false),
(4, 'Козлова',  'Анна',      'Игоревна',      402, '444444', 'EN', 100, false),
(3, 'Волков',   'Дмитрий',   'Олегович',      303, '555555', 'RU', 110, false)
ON CONFLICT (idcards) DO NOTHING;

-- Тестовые бронирования (демонстрация разных статусов)
-- Используем текущую дату для актуальности
INSERT INTO booking (dormitory_id, start_time, end_time, inidresidents, inidmachine, status) VALUES 
-- Подтверждённая запись Иванова — сегодня утром
(3, CURRENT_DATE + INTERVAL '8 hours',  CURRENT_DATE + INTERVAL '9 hours 30 minutes',  
    (SELECT id FROM residents WHERE idcards = '111111'), 
    (SELECT id FROM machines WHERE dormitory_id = 3 AND type_machine = 'Стиральная' AND number_machine = 1), 
    'Подтверждено'),
-- Ожидание подтверждения у Петровой — сегодня днём
(3, CURRENT_DATE + INTERVAL '14 hours', CURRENT_DATE + INTERVAL '15 hours 30 minutes', 
    (SELECT id FROM residents WHERE idcards = '222222'), 
    (SELECT id FROM machines WHERE dormitory_id = 3 AND type_machine = 'Стиральная' AND number_machine = 2), 
    'Ожидание подтверждения'),
-- Завершённая запись Сидорова — вчера
(4, CURRENT_DATE - INTERVAL '1 day' + INTERVAL '10 hours', CURRENT_DATE - INTERVAL '1 day' + INTERVAL '11 hours 30 minutes', 
    (SELECT id FROM residents WHERE idcards = '333333'), 
    (SELECT id FROM machines WHERE dormitory_id = 4 AND type_machine = 'Сушильная' AND number_machine = 1), 
    'Подтверждено'),
-- Отменённая запись Козловой — вчера
(4, CURRENT_DATE - INTERVAL '1 day' + INTERVAL '16 hours', CURRENT_DATE - INTERVAL '1 day' + INTERVAL '17 hours 30 minutes', 
    (SELECT id FROM residents WHERE idcards = '444444'), 
    (SELECT id FROM machines WHERE dormitory_id = 4 AND type_machine = 'Стиральная' AND number_machine = 3), 
    'Отменено'),
-- Ожидание у Волкова — завтра
(3, CURRENT_DATE + INTERVAL '1 day' + INTERVAL '11 hours', CURRENT_DATE + INTERVAL '1 day' + INTERVAL '12 hours 30 minutes', 
    (SELECT id FROM residents WHERE idcards = '555555'), 
    (SELECT id FROM machines WHERE dormitory_id = 3 AND type_machine = 'Сушильная' AND number_machine = 1), 
    'Ожидание');
